/*
 * LBA OpenUAV Questions
 *
 * Questions and answers of LBA OpenUAV for preparing to the exam.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"errors"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"
	"log"
	"net/http"
)

// DefaultApiService is a service that implents the logic for the DefaultApiServicer
// This service should implement the business logic for every endpoint for the DefaultApi API.
// Include any external packages or services that will be required by this service.
type DefaultApiService struct {
	db *mongo.Collection
}

// NewDefaultApiService creates a default api service
func NewDefaultApiService(mongoClient *mongo.Client) DefaultApiServicer {
	return &DefaultApiService{
		db: mongoClient.Database("lba").Collection("questions-all"),
	}
}

// GetAllQuestions -
func (s *DefaultApiService) GetAllQuestions(ctx context.Context) (ImplResponse, error) {
	return Response(200, find(s, bson.D{{}}, options.Find())), nil
}

// GetOneQuestion -
func (s *DefaultApiService) GetOneQuestion(ctx context.Context, type_ string) (ImplResponse, error) {
	// TODO - update GetOneQuestion with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, Question{}) or use other options such as http.Ok ...
	return Response(200, Question{}), nil
}

// GetQuestionById -
func (s *DefaultApiService) GetQuestionById(ctx context.Context, questionId int32) (ImplResponse, error) {
	// TODO - update GetQuestionById with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, Question{}) or use other options such as http.Ok ...
	return Response(200, findOne(s, questionId)), nil
}

// SetQuestionAnswered -
func (s *DefaultApiService) SetQuestionAnswered(ctx context.Context, questionId int32, inlineObject InlineObject) (ImplResponse, error) {
	// TODO - update SetQuestionAnswered with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	//return Response(204, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("SetQuestionAnswered method not implemented")
}

func findOne(s *DefaultApiService, questionId int32) Question {
	var elem Question
	if err := s.db.FindOne(context.TODO(), bson.D{{"_id", questionId}}).Decode(&elem); err != nil {
		log.Fatal(err)
	}

	return elem
}

func find(s *DefaultApiService, allQuery bson.D, findOptions *options.FindOptions) []*Question {
	cur, err := s.db.Find(context.TODO(), allQuery, findOptions)
	if err != nil {
		log.Fatal(err)
	}
	results := []*Question{}
	for cur.Next(context.TODO()) {
		var elem Question
		err := cur.Decode(&elem)
		if err != nil {
			log.Fatal(err)
		}
		results = append(results, &elem)
	}

	return results
}
