/*
 * LBA OpenUAV Questions
 *
 * Questions and answers of LBA OpenUAV for preparing to the exam.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"
	"log"
)

// DefaultApiService is a service that implents the logic for the DefaultApiServicer
// This service should implement the business logic for every endpoint for the DefaultApi API.
// Include any external packages or services that will be required by this service.
type DefaultApiService struct {
	db *mongo.Collection
}

// NewDefaultApiService creates a default api service
func NewDefaultApiService(mongoClient *mongo.Client) DefaultApiServicer {
	return &DefaultApiService{
		db: mongoClient.Database("lba").Collection("questions-all"),
	}
}

// GetAllQuestions -
func (s *DefaultApiService) GetAllQuestions(ctx context.Context) (ImplResponse, error) {
	return Response(200, find(s, bson.D{{}}, options.Find())), nil
}

// GetOneQuestion -
func (s *DefaultApiService) GetOneQuestion(ctx context.Context, type_ string) (ImplResponse, error) {
	question := findOne(s, bson.D{
		{"answers.guessedAsCorrect", bson.D{{"$ne", true}}},
		{"answers.correctAnswer", bson.D{{"$ne", true}}},
	})
	return Response(200, question), nil
}

// GetQuestionById -
func (s *DefaultApiService) GetQuestionById(ctx context.Context, questionId int32) (ImplResponse, error) {
	return Response(200, findOne(s, bson.D{{"_id", questionId}})), nil
}

// SetQuestionAnswered -
func (s *DefaultApiService) SetQuestionAnswered(ctx context.Context, questionId int32, answer AnswerPayload) (ImplResponse, error) {
	filter := bson.D{{"_id", questionId}, {"answers.id", answer.AnswerId}}
	update := bson.D{
		{"$set", bson.D{{"answers.$.guessedAsCorrect", true}}},
		{"$set", bson.D{{"comment", answer.Comment}}},
	}
	updateOne(s, filter, update)
	return Response(204, nil), nil
}

func findOne(s *DefaultApiService, query bson.D) Question {
	var elem Question
	if err := s.db.FindOne(context.TODO(), query).Decode(&elem); err != nil {
		log.Fatal(err)
	}

	return elem
}

func updateOne(s *DefaultApiService, filter bson.D, update bson.D) *mongo.UpdateResult {
	updateResult, err := s.db.UpdateOne(context.TODO(), filter, update)
	if err != nil {
		log.Fatal(err)
	}
	return updateResult
}

func find(s *DefaultApiService, allQuery bson.D, findOptions *options.FindOptions) []*Question {
	cur, err := s.db.Find(context.TODO(), allQuery, findOptions)
	if err != nil {
		log.Fatal(err)
	}
	results := []*Question{}
	for cur.Next(context.TODO()) {
		var elem Question
		err := cur.Decode(&elem)
		if err != nil {
			log.Fatal(err)
		}
		results = append(results, &elem)
	}

	return results
}
